export const SYSTEM_HTTP_RESPONSE_BUSINESS_ERROR = 'SYSTEM_HTTP_RESPONSE_BUSINESS_ERROR';
export const SYSTEM_HTTP_RESPONSE_SYSTEM_ERROR = 'SYSTEM_HTTP_RESPONSE_SYSTEM_ERROR';
export const SYSTEM_HTTP_RESPONSE_NOT_LOGIN = 'SYSTEM_HTTP_RESPONSE_NOT_LOGIN';
